### ISSUE TITLE
Minimum coverage not documented as integer or as percentage

### ISSUE THREAD

**Issue by dabrahams** [mattpolzin/swift-test-codecov#20]
Given that the action outputs fractional coverage, it's surprising that the minimum coverage can't be set to a non-integer.  It is also not documented as a percentage.  The ideal IMO would be to accept floating values, but at minimum the doc should be updated a bit.

Thanks!

**Comment by mattpolzin** [comment]
Yeah, this is a bit of an awkward disconnect between input and output.

After fixing the GitHub Action issue you were kind enough to prod me about I'll prepare an update that supports floating point values for minimum coverage.
